version: '3.9'
services:
  readmy.account.mongo:
    container_name: readmy.account.mongo
    restart: 'no'
    ports:
      - ${MONGO_EXTERNAL_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
