version: '3.9'
services:
  readmy.account:
    image: readmy.file-storage:latest
    container_name: readmy.file-storage
    restart: always
    env_file:
      - ./file-storage.env
    environment:
      PORT: ${PORT}
      NODE_ENV: production
    depends_on:
      - readmy.file-storage.mongo
    ports:
      - ${PORT}:${PORT}
    networks:
      - readmy.file-storage.network
        
  readmy.file-storage.mongo:
    image: mongo:4.4
    restart: always
    container_name: readmy.file-storage.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - readmy.mongo.file-storage:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:${MONGO_PORT}/?authSource=${MONGO_DB} --quiet
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - readmy.file-storage.network

volumes:
  readmy.mongo.file-storage:
    
networks:
  readmy.file-storage.network:
      driver: bridge
