version: '3.9'
services:
  readmy.test.blog.postgres:
    image: postgres:14-alpine
    restart: always
    container_name: readmy.test.blog.postgres
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
    ports:
      - ${TEST_POSTGRES_EXTERNAL_PORT}:${TEST_PGADMIN_PORT}

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${TEST_POSTGRES_USER} -d {TEST_POSTGRES_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
